server:
  port:8082

spring:
  devtools:
    restart:
      poll-interval: 2s
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/graduate_attendance
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



